name: Qlty Coverage

on:
  push:
    branches:
      - main

permissions:
  actions: write
  contents: read
  id-token: write

jobs:
  upload-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: 'go.mod'

      - name: Run tests
        run: go test -coverprofile=coverage.out

      - uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          token: ${{ secrets.QLTY_COVERAGE_TOKEN }}
          files: coverage/.resultset.json
